### ISSUE TITLE
Some signals not emitted on Godot 3.6

### ISSUE THREAD

**Issue by dannygaray60** [Iakobs/godot-google-play-game-services-android-plugin#12]
Hi, thanks for the plugin! I was testing it in godot 3.6 and the Snapshot signals are not emitted.

I have already tested the Sign-in functions and signals work fine, I have not tested the Leaderboards or Events, but trying to use Snapshot the signals do not work, but methods work, for example I can save snapshots or open the dialog popup to select a snapshot.

**Comment by Iakobs** [comment]
Hi! Thanks for using the plugin! I'm sorry to hear that signals are not working properly. Maybe it's because I haven't updated the plugin to Godot 3.6.

I don't have the bandwith to test it now, but maybe you can try with [this version of the `aar` file ](https://github.com/user-attachments/files/17521508/3.6.zip) of the plugin, which I compiled with Godot 3.6 SDK. Please let me know if this fixes the issue!

**Comment by dannygaray60** [comment]
I tried, doesn't work, but if I use load_snapshot directly it emits the signal, so the issue is with the native dialog used to select a snapshot

**Comment by Iakobs** [comment]
I see, now I know where's the problem. That part is implemented a bit different due to restrictions of the Godot Android SDK. I will try to get a look as soon as I can, but in the meantime, do you see anything relevant in the logs?

If you're curious and you know kotlin and want to give it a look, the flow in  the code of the plugin is:

1. You call the [`snapshotsShowSavedGames` method](https://github.com/Iakobs/godot-google-play-game-services-android-plugin/blob/main/app/src/main/java/com/jacobibanez/godot/gpgs/GodotGooglePlayGameServices.kt#L177)
2. That goes to the `SnapshotsProxy` class, that calls the Google sdk [here](https://github.com/Iakobs/godot-google-play-game-services-android-plugin/blob/main/app/src/main/java/com/jacobibanez/godot/gpgs/snapshots/SnapshotsProxy.kt#L51)
3. That opens the dialog in your game, and when you select a Snapshot, it returns an `Intent` to the plugin, that is consumed in the [`onActivityResult` method](https://github.com/Iakobs/godot-google-play-game-services-android-plugin/blob/main/app/src/main/java/com/jacobibanez/godot/gpgs/snapshots/SnapshotsProxy.kt#L32), which in turn, [emits the `snapshotsGameLoaded` signal](https://github.com/Iakobs/godot-google-play-game-services-android-plugin/blob/main/app/src/main/java/com/jacobibanez/godot/gpgs/snapshots/SnapshotsProxy.kt#L112) with the Snapshot.

You should see these logs in logcat while doing all of that:

1. `Showing save games`
2. `Loading snapshot with name $fileName.`

Let me know if you find anything else, I will keep you posted as well if I find anything!

**Comment by Iakobs** [comment]
Hi @dannygaray60 I've found the problem and fixed it! You have a new release of the plugin [here](https://github.com/Iakobs/godot-google-play-game-services-android-plugin/releases/tag/v2.2.0). Hope it works now! Let me know if it was fixed so we can close the issue 😄

**Comment by dannygaray60** [comment]
wow! that was fast, thank you so much! it's working well now! Tested achievements, snapshots, and sign-in, methods and signals working :D

**Comment by Iakobs** [comment]
I'm happy to hear it's working!
