### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Miskler** [Iakobs/godot-google-play-game-services-android-plugin#2]
Hi! You advised me to update the grandle SDK, but in order to do this I had to update Android Studio, but after that the minimum SDK to use became 8.0.1

Now I have an error popping up `AndroidManifest.xml`
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:dist="http://schemas.android.com/apk/distribution" package="basePackage" split="installTime">
  <dist:module dist:type="asset-pack">
    <dist:fusing dist:include="true" />    <dist:delivery>
      <dist:install-time/>
    </dist:delivery>
  </dist:module>
</manifest>

```
![image](https://user-images.githubusercontent.com/69055489/236607507-ef2ca1dc-b9c1-4a8e-9264-f86c50b47187.png)
Do you not know how to fix these errors?
![image](https://user-images.githubusercontent.com/69055489/236607579-5fae5b6f-8c0f-4d26-98ca-c32f7e33f946.png)

**Comment by Miskler** [comment]
I have installed the Godot 3.6.beta export template

This is certainly not a complete solution to the problem, but as a temporary patch will do :)

**Comment by Iakobs** [comment]
As far as I know, the gradle sdk doesn't require android studio for updating. Android Studio is just an aid for developing the plugin, but when it comes to use the plugin in your godot game, you can manually modify the template that godot provides with any text editor.

That being said, building the gradle project of your game's `android/build` folder is not going to work because that is merely a template and Godot replaces some information when you run the game in an emulator or export it as an .aab or .apk file, if that makes sense, meaning that is normal to get errors when building the `android/build` folder.

Also, are you using Godot 3.5? The template with the changes I mention in the docs should work fine. Also, the update of the gradle plugin and gradle API is just recommended, not mandatory.

Hope this helps and thanks again for your interest in our plugin, it helps us a lot having this issues in an early stage of development 😃

**Comment by Miskler** [comment]
Out of my own stupidity, I decided to upgrade to the most up-to-date parameters and paid for it... https://github.com/godotengine/godot/issues/76776

Thank you for your help!

**Comment by Iakobs** [comment]
No worries at all! Glad it got sorted out 😃 I'm going to close the issue.
